<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('用户数据')
                // reject('出错啦')
            }, 1000);
        })

        //调用then方法
        const result = p.then(value => {
            console.log(value);
            // 1.如果非promise类型的属性 return 一个 undefined 状态也为成功
            // 2. 是promise对象 根据这个promise成功还是失败 来决定这个then的返回 是成功还是失败
            // return new Promise((resolve, reject) => {
            //     resolve('ok')
            // })
            // throw new Error('出错啦!')
            // throw '出错啦!'
            // 返回值由上一个promise对象的返回值或者非promise的值决定
        }, reason => {
            console.warn(reason);
        })
        console.log(result); //then方法返回对象也是一个promise对象 对象状态由回调函数执行结果决定
        //如果返回调函数的返回结果为非promise的类型的属性 状态为成功 返回值为对象成功值
        // catch方法是用来指定回调失败的方法 没有他只用then当然也能使用
        const p2 = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject('出错啦！')
            }, 1000);
        })

        p2.catch(function (reason) {
            console.log(reason);
        })
    </script>
</body>

</html>